config/routes.rb
Rails.application.routes.draw do
  get :sign_in, to: 'sessions#new'
  get 'auth/facebook/callback', to: 'sessions#auth_callback'
  delete :sign_out, to: 'sessions#destroy'

  namespace :api, defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :monsters, only: [:index, :show, :create, :update, :destroy]
      resources :teams, only: [:index, :show, :create, :update, :destroy]
    end
  end

  resources :monsters, except: [:show]
  resources :teams

  root 'monsters#index'
end

app/views/shared/_flash.html.haml
.row
  .col-md-12
    - flash.each do |name, msg|
      %div{class: "alert alert-row alert-dismissible alert-#{name}"}
        %button.close{'data-dismiss' => 'alert', :type => 'button'}
          %span{'aria-hidden' => 'true'} ×
          %span.sr-only Close
        = msg

app/views/shared/_navbar.html.haml
.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to 'Rubymon', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: ('active' if controller_name == 'monsters')}
          = link_to 'Monsters', monsters_path
        %li{class: ('active' if controller_name == 'teams')}
          = link_to 'Teams', teams_path

      %ul.nav.navbar-nav.navbar-right
        %li
          %p.navbar-text Signed in as #{current_user.name}
        %li= link_to 'Sign Out', sign_out_path, method: :delete, class: 'btn btn-default navbar-btn'